--- #YAML:1.0
name: Solaris-Disk-SVM
version: 0.01
author:
  - Jérôme Fenal <jfenal@free.fr>
abstract: ~
license: perl
requires:
  Carp: 0
  Solaris::Disk::Mnttab: 0
  Solaris::Disk::VTOC: 0
  Term::ANSIColor: 0
  perl: 5.6.1
recommends:
  Test::More: 0
provides:
  Solaris::Disk::SVM:
    file: lib/Solaris/Disk/SVM.pm
    version: 0.01
generated_by: Module::Build version 0.25
